env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - http://localhost:9898
  parameters:
    failOnError: true
    progressToStdout: true
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: http://localhost:9898
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: zap_scan_report.xml
    reportTitle: ZAP Scanning Report
    template: traditional-xml
  type: report
