CREATE TABLE states (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    workflow_priority NUMBER DEFAULT 0,
    deleted NUMBER(1) DEFAULT 0,
    CONSTRAINT uk_state_name UNIQUE (name)
);

CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    deleted NUMBER(1) DEFAULT 0,
    CONSTRAINT uk_role_name UNIQUE (name)
);

CREATE TABLE teams (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    creation_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    deleted NUMBER(1) DEFAULT 0,
    CONSTRAINT uk_team_name UNIQUE (name)
);

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR2(100) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    role_id NUMBER,
    team_id NUMBER,
    deleted NUMBER(1) DEFAULT 0,
    CONSTRAINT uk_username UNIQUE (phone_number),
    CONSTRAINT fk_users_team FOREIGN KEY (team_id) REFERENCES teams(id),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE projects (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    creation_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    due_date TIMESTAMP,
    state_id NUMBER,
    deleted NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_projects_state FOREIGN KEY (state_id) REFERENCES states(id)
);

CREATE TABLE sprints (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    creation_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    due_date TIMESTAMP,
    state_id NUMBER,
    project_id NUMBER,
    deleted NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_sprints_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_sprints_state FOREIGN KEY (state_id) REFERENCES states(id)
);

CREATE TABLE todo (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    creation_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    due_date TIMESTAMP,
    state_id NUMBER,
    sprint_id NUMBER,
    user_id NUMBER,
    story_points NUMBER DEFAULT 0,
    deleted NUMBER(1) DEFAULT 0,
    CONSTRAINT uk_todo_title UNIQUE (title),
    CONSTRAINT fk_todo_sprint FOREIGN KEY (sprint_id) REFERENCES sprints(id),
    CONSTRAINT fk_todo_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_todo_state FOREIGN KEY (state_id) REFERENCES states(id)
);

INSERT INTO states (name) VALUES ('New');
INSERT INTO states (name) VALUES ('In Progress');
INSERT INTO states (name) VALUES ('Review');
INSERT INTO states (name) VALUES ('Done');
INSERT INTO states (name) VALUES ('Blocked');

INSERT INTO roles (name) VALUES ('Administrator');
INSERT INTO roles (name) VALUES ('Project Manager');
INSERT INTO roles (name) VALUES ('Developer');
INSERT INTO roles (name) VALUES ('QA Engineer');
INSERT INTO roles (name) VALUES ('Team Lead');

INSERT INTO teams (name) VALUES ('Backend Team');
INSERT INTO teams (name) VALUES ('Frontend Team');
INSERT INTO teams (name) VALUES ('QA Team');
INSERT INTO teams (name) VALUES ('DevOps Team');
INSERT INTO teams (name) VALUES ('Mobile Team');

INSERT INTO users (username, name, role_id, team_id) 
SELECT 'sofia.moreno', 'Sofia Moreno', r.id, t.id
FROM roles r, teams t 
WHERE r.name = 'Project Manager' AND t.name = 'Backend Team';

INSERT INTO users (username, name, role_id, team_id) 
SELECT 'omar.sanchez', 'Omar Sanchez', r.id, t.id
FROM roles r, teams t 
WHERE r.name = 'Team Lead' AND t.name = 'Frontend Team';

INSERT INTO users (username, name, role_id, team_id) 
SELECT 'jimena.carmona', 'Jimena Carmona', r.id, t.id
FROM roles r, teams t 
WHERE r.name = 'Developer' AND t.name = 'Backend Team';

INSERT INTO users (username, name, role_id, team_id) 
SELECT 'edgar.villa', 'Edgar Villa', r.id, t.id
FROM roles r, teams t 
WHERE r.name = 'QA Engineer' AND t.name = 'QA Team';

INSERT INTO projects (name, due_date, state_id) 
SELECT 'Sistema de Inventario', TIMESTAMP '2025-12-31 23:59:59', s.id
FROM states s WHERE s.name = 'In Progress';

INSERT INTO projects (name, due_date, state_id) 
SELECT 'Portal de Clientes', TIMESTAMP '2025-06-30 23:59:59', s.id
FROM states s WHERE s.name = 'New';

INSERT INTO projects (name, due_date, state_id) 
SELECT 'API de Pagos', TIMESTAMP '2025-09-30 23:59:59', s.id
FROM states s WHERE s.name = 'In Progress';

INSERT INTO projects (name, due_date, state_id) 
SELECT 'Migracion Cloud', TIMESTAMP '2025-04-30 23:59:59', s.id
FROM states s WHERE s.name = 'Review';

INSERT INTO sprints (name, due_date, state_id, project_id) 
SELECT 'Sprint 1 - Base de Datos', TIMESTAMP '2025-03-31 23:59:59', s.id, p.id
FROM states s, projects p 
WHERE s.name = 'In Progress' AND p.name = 'Sistema de Inventario';

INSERT INTO sprints (name, due_date, state_id, project_id) 
SELECT 'Sprint 2 - Modulos Core', TIMESTAMP '2025-04-30 23:59:59', s.id, p.id
FROM states s, projects p 
WHERE s.name = 'New' AND p.name = 'Sistema de Inventario';

INSERT INTO sprints (name, due_date, state_id, project_id) 
SELECT 'Sprint Portal - Auth', TIMESTAMP '2025-03-15 23:59:59', s.id, p.id
FROM states s, projects p 
WHERE s.name = 'In Progress' AND p.name = 'Portal de Clientes';

INSERT INTO sprints (name, due_date, state_id, project_id) 
SELECT 'Sprint API - Integracion', TIMESTAMP '2025-04-15 23:59:59', s.id, p.id
FROM states s, projects p 
WHERE s.name = 'New' AND p.name = 'API de Pagos';

INSERT INTO sprints (name, due_date, state_id, project_id) 
SELECT 'Sprint Cloud - Setup', TIMESTAMP '2025-03-20 23:59:59', s.id, p.id
FROM states s, projects p 
WHERE s.name = 'Review' AND p.name = 'Migracion Cloud';

INSERT INTO todo (title, description, due_date, state_id, sprint_id, user_id, story_points)
SELECT 'Diseno BD Inventario', 
       'Crear esquema inicial de base de datos para sistema de inventario',
       TIMESTAMP '2025-03-15 23:59:59',
       s.id,
       sp.id,
       u.id,
       5
FROM states s, sprints sp, users u
WHERE s.name = 'In Progress' 
AND sp.name = 'Sprint 1 - Base de Datos'
AND u.username = 'sofia.moreno';

INSERT INTO todo (title, description, due_date, state_id, sprint_id, user_id, story_points)
SELECT 'Sistema de Autenticacion',
       'Implementar autenticacion con tokens JWT',
       TIMESTAMP '2025-03-20 23:59:59',
       s.id,
       sp.id,
       u.id,
       8
FROM states s, sprints sp, users u
WHERE s.name = 'New'
AND sp.name = 'Sprint 1 - Base de Datos'
AND u.username = 'jimena.carmona';

INSERT INTO todo (title, description, due_date, state_id, sprint_id, user_id, story_points)
SELECT 'Maquetacion Portal',
       'Crear disenos UI/UX para portal de clientes',
       TIMESTAMP '2025-03-10 23:59:59',
       s.id,
       sp.id,
       u.id,
       3
FROM states s, sprints sp, users u
WHERE s.name = 'Review'
AND sp.name = 'Sprint Portal - Auth'
AND u.username = 'omar.sanchez';

INSERT INTO todo (title, description, due_date, state_id, sprint_id, user_id, story_points)
SELECT 'Documentacion API',
       'Documentar endpoints de API usando OpenAPI',
       TIMESTAMP '2025-04-10 23:59:59',
       s.id,
       sp.id,
       u.id,
       5
FROM states s, sprints sp, users u
WHERE s.name = 'New'
AND sp.name = 'Sprint API - Integracion'
AND u.username = 'jimena.carmona';

INSERT INTO todo (title, description, due_date, state_id, sprint_id, user_id, story_points)
SELECT 'Configuracion AWS',
       'Realizar setup inicial de servicios AWS',
       TIMESTAMP '2025-03-15 23:59:59',
       s.id,
       sp.id,
       u.id,
       13
FROM states s, sprints sp, users u
WHERE s.name = 'In Progress'
AND sp.name = 'Sprint Cloud - Setup'
AND u.username = 'edgar.villa';
