package com.springboot.MyTodoList.model;


import javax.persistence.*;
import java.time.OffsetDateTime;

/*
    representation of the TODOITEM table that exists already
    in the autonomous database


    CREATE TABLE todo (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    creation_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    due_date TIMESTAMP,
    state_id NUMBER,
    sprint_id NUMBER,
    user_id NUMBER,
    project_id NUMBER,
    story_points NUMBER DEFAULT 0,
    priority enum('Low', 'Medium', 'High') DEFAULT 'Low',
    deleted NUMBER(1) DEFAULT 0,
    CONSTRAINT uk_todo_title UNIQUE (title),
    CONSTRAINT fk_todo_project FOREIGN KEY (project_id) REFERENCES projects(id),
    CONSTRAINT fk_todo_sprint FOREIGN KEY (sprint_id) REFERENCES sprints(id),
    CONSTRAINT fk_todo_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_todo_state FOREIGN KEY (state_id) REFERENCES states(id)
);
 */
@Entity
@Table(name = "TODOITEM")
public class ToDoItem {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    int ID;

    @Column(name = "TITLE")
    String title;

    @Column(name = "DESCRIPTION")
    String description;

    @Column(name = "CREATION_TS")
    OffsetDateTime creation_ts;

    @Column(name = "DUE_DATE")
    OffsetDateTime due_date;

    @Column(name = "STATE_ID")
    int state_id;

    @Column(name = "SPRINT_ID")
    int sprint_id;

    @Column(name = "USER_ID")
    int user_id;

    @Column(name = "PROJECT_ID")
    int project_id;

    @Column(name = "STORY_POINTS")
    int story_points;

    @Column(name = "PRIORITY")
    String priority;

    @Column(name = "DELETED")
    boolean deleted;

    @Column(name = "done")
    boolean done;

    public ToDoItem(){

    }
    public ToDoItem(int ID, String title, String description, OffsetDateTime creation_ts, OffsetDateTime due_date, int state_id, int sprint_id, int user_id, int project_id, int story_points, String priority, boolean deleted, boolean done) {
        this.ID = ID;
        this.title = title;
        this.description = description;
        this.creation_ts = creation_ts;
        this.due_date = due_date;
        this.state_id = state_id;
        this.sprint_id = sprint_id;
        this.user_id = user_id;
        this.project_id = project_id;
        this.story_points = story_points;
        this.priority = priority;
        this.deleted = deleted;
        this.done = done;
    }

    @Override
    public String toString() {
        return "ToDoItem{" +
                "ID=" + ID +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", creation_ts=" + creation_ts +
                ", due_date=" + due_date +
                ", state_id=" + state_id +
                ", sprint_id=" + sprint_id +
                ", user_id=" + user_id +
                ", project_id=" + project_id +
                ", story_points=" + story_points +
                ", priority='" + priority + '\'' +
                ", deleted=" + deleted +
                ", done=" + done +
                '}';
    }

    public int getID() {
        return ID;
    }

    public String getTitle() {
        return title;
    }

    public String getDescription() {
        return description;
    }

    public OffsetDateTime getCreation_ts() {
        return creation_ts;
    }

    public OffsetDateTime getDue_date() {
        return due_date;
    }

    public int getState_id() {
        return state_id;
    }

    public int getSprint_id() {
        return sprint_id;
    }

    public int getUser_id() {
        return user_id;
    }

    public int getProject_id() {
        return project_id;
    }

    public int getStory_points() {
        return story_points;
    }

    public String getPriority() {
        return priority;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public boolean isDone() {
        return done;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setCreation_ts(OffsetDateTime creation_ts) {
        this.creation_ts = creation_ts;
    }

    public void setDue_date(OffsetDateTime due_date) {
        this.due_date = due_date;
    }

    public void setState_id(int state_id) {
        this.state_id = state_id;
    }

    public void setSprint_id(int sprint_id) {
        this.sprint_id = sprint_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

    public void setProject_id(int project_id) {
        this.project_id = project_id;
    }

    public void setStory_points(int story_points) {
        this.story_points = story_points;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public void setDone(boolean done) {
        this.done = done;
    }

}
